import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { RootLayout } from '@/layouts'
import { getUser } from '@/api'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

const isLoggedIn = async () => {
  try {
    const token = cookies()?.get('token')?.value
    const data = await getUser({
      headers: {
        'Cookie': `token=${token}`
      }
    })
    return {
      ...data,
      isLoggedIn: true
    }
  } catch (err) {
    return {
      isLoggedIn: false
    }
  }
}

export const metadata: Metadata = {
  title: 'Պրոմո',
  description: 'Generated by create next app',
}

const Root = async ({
  children,
}: {
  children: React.ReactNode
}) => {
  const user = await isLoggedIn()

  return (
    <html lang="hy">
      <body className={inter.className}>
        <RootLayout user={user}>
          {children}
        </RootLayout>
      </body>
    </html>
  )
}

export default Root