import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { RootLayout } from '@/layouts'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Պրոմո',
  description: 'Generated by create next app',
}

const Root = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang="hy">
      <body className={inter.className}>
        <RootLayout>
          {children}
        </RootLayout>
      </body>
    </html>
  )
}

export default Root